[auth.users.admin]
name = "Dashboard Admin"
role = "admin"
password_hash = "pbkdf2_sha256$600000$OpXjF6iXaMhCC9pWuTiWlA$vFjEStYZfHvc2ZEBnbNADI6R2fY8rGS2qwInlYon43Y"


[auth.users.batzorig]
name = "Batzorig boss"
role = "admin"
password_hash = "pbkdf2_sha256$600000$t8R0AtDE24CPXnsWomRA8w$_n7lSFGzx27LsrON0jJr-vUl161TxaAAs89uk4IpgrM"
